In [6]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import os

In [10]:
# os.listdir('C:/Users/Daniel Lara/Downloads')

In [16]:
df = pd.read_excel("C:/Users/Daniel Lara/Downloads/Caso Excel Loctite (1).xlsx")
df

,Profit Center,IB Segment,Customer Code,cliente,Main Material,2020.,2021.,2022.
0,ACM General Mfg.&Maintenance Operative,ACM Glass Manuf.(/Fi,2196633.0,Cliente 18,TEROSON BOND180 TRUE PL FC600ML,878500286.0,7.884244e+08,335768674
1,ACM General Mfg.&Maintenance Operative,ACM Glass Manuf.(/Fi,2196633.0,Cliente 18,TEROSON PU 9092 PL BIS 600 g,681300204.0,3.811293e+08,265505988
2,ACM General Mfg.&Maintenance Operative,ACM Glass Manuf.(/Fi,2370697.0,Cliente 35,High level posting for rebates,399197171.0,1.993819e+08,167132967
3,ACM General Mfg.&Maintenance Operative,ACM Glass Manuf.(/Fi,2370697.0,Cliente 35,LOCTITE AA 312 BO50ML DE/EN,647815344.0,2.175627e+08,271315150
4,ACM General Mfg.&Maintenance Operative,ACM Glass Manuf.(/Fi,2370697.0,Cliente 35,LOCTITE SF 736 AE6OZEN,802103077.0,5.654660e+08,582327366
...,...,...,...,...,...,...,...,...
7863,ACM General Mfg.&Maintenance Operative,FI postings,882725.0,Cliente 204,High level posting for rebates,181004562.0,1.710764e+08,666565319
7864,ACM General Mfg.&Maintenance Operative,FI postings,888865.0,Cliente 131,High level posting for rebates,856138735.0,8.626051e+08,747579984
7865,ACM General Mfg.&Maintenance Operative,FI postings,914236.0,Cliente 126,High level posting for rebates,366362498.0,3.786712e+08,847362078
7866,ACM General Mfg.&Maintenance Operative,FI postings,943629.0,Cliente 66,High level posting for rebates,510082704.0,9.051634e+08,423014421
7867,Total general,NaN,NaN,NaN,NaN,NaN,1.180464e+11,56975143808

In [31]:
A = df.groupby(by = "cliente")[["2020.","2021."]].sum()
A["Crecimiento"] = (A["2021."] - A["2020."])
A["%"]= A["Crecimiento"]/A["2020."]
A.sort_values("%",ascending=False).head(5)

                   2020.        2021.  Crecimiento         %
cliente
Cliente 32   125070819.0  942164205.0  817093386.0  6.533046
Cliente 151  105124418.0  544166169.0  439041751.0  4.176401
Cliente 154  206695404.0  909179431.0  702484027.0  3.398644
Cliente 29   343901615.0  681180697.0  337279082.0  0.980743
Cliente 164  427270936.0  807875792.0  380604856.0  0.890781